In [ ]:
Question 1

In [ ]:
the Gauss-Seidel method converges faster than the Jacobi method as shown :
The Gauss-Seidel uses updated values as soon as they are available. 


In [ ]:
p1=(p2+p3)/4
p2=(p1+p3+p4+p5)/5
p3=(p1+p2+p6+p5)/5
p4=(p2+p5+p7+p8)/5
p5=(p2+p3+p4+p6+p8+p9)/6
p6=(p5+p3+p9+p10)/5
p7=(4+p4+p8)/4
p8=(5+p4+p5+p7+p9)/5
p9=(5+p6+p5+p8+p10)/5
p10=(4+p6+p9)/4





In [ ]:
JACOBI METHOD

In [16]:
import numpy as np
from numpy.linalg import inv,solve
def jacobi(A,b,N):
    x= np.zeros_like(b)
    D=np.diag(A)
    A_Without_D= A-np.diag(D)
    for i in range (N):
        x= inv(np.diag(D)).dot(b- (A_Without_D).dot(x))
    return x
A=[[4,-1,-1,0,0,0,0,0,0,0],[-1,5,-1,-1,-1,0,0,0,0,0],[-1,-1,5,0,-1,-1,0,0,0,0],[0,-1,0,5,-1,0,-1,-1,0,0],[0,-1,-1,-1,6,-1,0,-1,-1,0],[0,0,-1,0,-1,5,0,0,-1,-1],[0,0,0,-1,0,0,4,-1,0,0],[0,0,0,-1,-1,0,-1,5,-1,0],[0,0,0,0,-1,-1,0,-1,5,-1],[0,0,0,0,0,-1,0,0,-1,4]]
b=[[0],[0],[0],[0],[0],[0],[1],[1],[1],[1]]

# print (A)
print(jacobi(A,b,20))
solve(A,b)

[[0.08857212]
 [0.17784873]
 [0.17784873]
 [0.29549578]
 [0.33008541]
 [0.29549578]
 [0.453278  ]
 [0.51902519]
 [0.51902519]
 [0.453278  ]]


array([[0.09019608],
       [0.18039216],
       [0.18039216],
       [0.29803922],
       [0.33333333],
       [0.29803922],
       [0.45490196],
       [0.52156863],
       [0.52156863],
       [0.45490196]])

In [ ]:
GAUSS-SEIDEL METHOD

In [15]:
import numpy as np
from numpy.linalg import inv,solve
def siedel(A,b,N):
    x= np.zeros_like(b)
    LD=np.tril(A)
    U=A -LD
    LDinv= inv(LD)
    for i in range (N):
        x= LDinv @ (b- U@x)
    return x
A=[[4,-1,-1,0,0,0,0,0,0,0],[-1,5,-1,-1,-1,0,0,0,0,0],[-1,-1,5,0,-1,-1,0,0,0,0],[0,-1,0,5,-1,0,-1,-1,0,0],[0,-1,-1,-1,6,-1,0,-1,-1,0],[0,0,-1,0,-1,5,0,0,-1,-1],[0,0,0,-1,0,0,4,-1,0,0],[0,0,0,-1,-1,0,-1,5,-1,0],[0,0,0,0,-1,-1,0,-1,5,-1],[0,0,0,0,0,-1,0,0,-1,4]]
b=[[0],[0],[0],[0],[0],[0],[1],[1],[1],[1]]

# print (A)
print(siedel(A,b,20))
solve(A,b)

[[0.09016401]
 [0.18034936]
 [0.1803558 ]
 [0.29800286]
 [0.33329375]
 [0.2980128 ]
 [0.45488217]
 [0.52154221]
 [0.52154619]
 [0.45488975]]


array([[0.09019608],
       [0.18039216],
       [0.18039216],
       [0.29803922],
       [0.33333333],
       [0.29803922],
       [0.45490196],
       [0.52156863],
       [0.52156863],
       [0.45490196]])

In [ ]:
The Gauss-Seidel uses updated values as soon as they are available. 
the Gauss-Seidel method converges faster than the Jacobi method.

In [ ]:
Question 2

In [18]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_normalize = x / x.max()
    return fac, x_normalize
x = np.array([1, 1, 1])
A = np.array([[0, 1,2], 
              [0.5, 0,0],[0, 0.25,0]])

for i in range(8):
    x = np.dot(A, x)
    lambda_1, x = normalize(x)
    
print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.9285714285714286
Eigenvector: [1.         0.53846154 0.16346154]


In [26]:
from numpy import linalg as LA

w, v = LA.eig(np.array([[0, 1,2], 
              [0.5, 0,0],[0, 0.25,0]]))
print(w)
print(v)

[ 0.88464618+0.j        -0.44232309+0.2948714j -0.44232309-0.2948714j]
[[-0.86227396+0.j          0.69332593+0.j          0.69332593-0.j        ]
 [-0.48735527+0.j         -0.54259608-0.36171765j -0.54259608+0.36171765j]
 [-0.13772604+0.j          0.11796101+0.28307982j  0.11796101-0.28307982j]]


In [19]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n
x = np.array([1, 1, 1])
A = np.array([[0, 6,8], 
              [0.5, 0,0],[0, 0.5,0]])

for i in range(8):
    x = np.dot(A, x)
    lambda_1, x = normalize(x)
    
print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.8600746268656718
Eigenvector: [1.         0.26880642 0.05892678]


In [27]:
from numpy import linalg as LA

w, v = LA.eig(np.array([[0, 6,8], 
              [0.5, 0,0],[0, 0.5,0]]))
print(w)
print(v)

[ 2.         -0.99999998 -1.00000002]
[[-0.96836405  0.87287156 -0.87287156]
 [-0.24209101 -0.43643579  0.43643578]
 [-0.06052275  0.2182179  -0.21821788]]
